LearningManagementSystem/Controllers/StudentProfileController.cs
using LearningManagementSystem.Repositories.ApplicationUsers;
using LearningManagementSystem.Repositories.AssignmentSubmissions;
using LearningManagementSystem.Repositories.AssignmentSubmissions.Dtos;
using LearningManagementSystem.Repositories.Attachments;
using LearningManagementSystem.Repositories.Students;
using LearningManagementSystem.Repositories.Subjects;
using LearningManagementSystem.ViewModels;
using Microsoft.AspNet.Identity;
using System;
using System.IO;
using System.Web;
using System.Web.Mvc;

namespace LearningManagementSystem.Controllers
{
    [Authorize]
    public class StudentProfileController : Controller
    {
        private readonly IApplicationUserRepository _repository;
        private readonly IStudentRepository _studentRepository;
        private readonly ISubjectRepository _subjectRepository;
        private readonly IAttachmentRepository _attachmentRepository;
        private readonly IAssignmentSubmissionRepository _assignmentSubmissionRepository;

        public StudentProfileController(IApplicationUserRepository repository,
            IStudentRepository studentRepository,
            ISubjectRepository subjectRepository,
            IAttachmentRepository attachmentRepository,
            IAssignmentSubmissionRepository assignmentSubmissionRepository)
        {
            _repository = repository;
            _studentRepository = studentRepository;
            _subjectRepository = subjectRepository;
            _attachmentRepository = attachmentRepository;
            _assignmentSubmissionRepository = assignmentSubmissionRepository;
        }

        // GET: StudentProfile
        public ActionResult Index()
        {
            var currentuserId = User.Identity.GetUserId();
            var user = _repository.GetUserById(currentuserId);

            if (!user.IsStudent)
                return View("Unauthorized");

            var student = _studentRepository.GetStudentByCurrentUserId(user.Id);
            var subjectDtos = _subjectRepository.GetSubjectsByCourseId(student.CourseId);
            student.Course.Subjects = subjectDtos;
            return View(student);
        }

        public ActionResult Submission(int studentId, int courseId, int subjectId)
        {
            var student = _studentRepository.GetById(studentId);
            var subject = _subjectRepository.GetById(subjectId);
            var attachments = _attachmentRepository.GetBySubjectId(subjectId);
            return View(new ViewAttachmentsForStudentVM
            {
                Student = student,
                Subject = subject,
                Attachments = attachments
            });
        }

        public ActionResult UploadFile(HttpPostedFileBase newFile, int studentId, int attachmentId, int subjectId)
        {
            var fileName = $"studentId_{studentId}_attachmentId_{attachmentId}_subjectId_{subjectId}_{DateTime.Now.ToString("ddMMyyyyhhmmsstt")}.{newFile.FileName.Split('.')[1].Trim()}";

            if (newFile != null && newFile.ContentLength > 0)
            {
                string root = @"C:\Attachments\Submissions";

                if (!Directory.Exists(root))
                    Directory.CreateDirectory(root);

                root = root + "\\" + fileName;

                newFile.SaveAs(root);
            }

            var created = _assignmentSubmissionRepository.Create(new CreateAssignmentSubmissionDto {
                StudentId = studentId,
                AttachmentId = attachmentId,
                SubjectId = subjectId,
                CreatedDate = DateTime.Now,
                FileName = fileName,
            });

            return View("Index", "Home");
        }

        public void DownloadAssignment(string fileName)
        {
            var fileExtension = fileName.Split('.')[1].Trim();

            Response.Clear();
            Response.ContentType = "application/" + fileExtension;
            Response.AppendHeader("Content-Disposition", String.Format("{0}; filename={0}", fileName));
            Response.TransmitFile(string.Format(@"C:\Attachments\{0}", fileName));
            Response.End();
        }

    }
}

LearningManagementSystem/Views/Shared/_Layout.cshtml
@using LearningManagementSystem.Models.Enums
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("LMS", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @if (Session["isEmployee"] != null)
                    {
                        if ((bool)Session["isEmployee"])
                        {
                            if (Session["designation"].ToString() == Designation.GeneralManager.ToString())
                            {
                                <li>@Html.ActionLink("Courses", "Index", "Courses")</li>
                                <li>@Html.ActionLink("Subjects", "Index", "Subjects")</li>
                                <li>@Html.ActionLink("Students", "Index", "Students")</li>
                                <li>@Html.ActionLink("Employees", "Index", "Employees")</li>
                            }

                            if (Session["designation"].ToString() == Designation.CourseCoordinator.ToString())
                            {
                                var employeeId = Session["employeeId"].ToString();

                                var courseCoordinatorCourseId = Session["CourseCoordinatorCourseId"].ToString();

                                <li>@Html.ActionLink("Subjects", "Index", "Subjects")</li>
                                <li>@Html.ActionLink("Students", "Index", "Students")</li>
                                <li><a href="@Url.Action("Index", "Attachments", new { employeeId = employeeId, courseId = courseCoordinatorCourseId })">Attachment Uploading Panel</a></li>
                            }

                            if (Session["designation"].ToString() == Designation.Lecturer.ToString())
                            {
                                var employeeId = Session["employeeId"].ToString();
                                var _employeeId = Convert.ToInt16(employeeId);


                                var lectureSubjectId = Session["LecturerSubjectId"].ToString();
                                var _lectureSubjectId = Convert.ToInt16(lectureSubjectId);

                                <li><a href="@Url.Action("Corrections", "Employees", new { employeeId = employeeId })">Assignments to Correct</a></li>
                            }
                        }
                    }

                    @if (Session["isStudent"] != null)
                    {
                        if ((bool)Session["isStudent"])
                        {
                            <li>@Html.ActionLink("Student Profile", "Index", "StudentProfile")</li>
                        }
                    }

                    <li>@Html.ActionLink("Results", "Results", "Students")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>