LearningManagementSystem/Models/Subject.cs
using LearningManagementSystem.Models.Enums;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;

namespace LearningManagementSystem.Models
{
    public class Subject
    {
        [Required]
        public int Id { get; set; }

        [Required]
        [StringLength(100)]
        public string Title { get; set; }

        [Required]
        public Semester Semester { get; set; }

        [Required]
        public int CourseId { get; set; }

        public Course Course { get; set; }

        public ICollection<Employee> Employees { get; set; } // Lecturer only

        public Subject()
        {
            Employees = new Collection<Employee>();
        }

    }
}

LearningManagementSystem/Controllers/SubjectsController.cs
using AutoMapper;
using LearningManagementSystem.Models;
using LearningManagementSystem.Repositories.Courses;
using LearningManagementSystem.Repositories.Subjects;
using LearningManagementSystem.Repositories.Subjects.Dtos;
using System.Collections.Generic;
using System.Web.Mvc;

namespace LearningManagementSystem.Controllers
{
    public class SubjectsController : Controller
    {
        private readonly ISubjectRepository _repository;
        private readonly ICourseRepository _courseRepository;
        private readonly IMapper _mapper;

        public SubjectsController(ISubjectRepository repository,  
            ICourseRepository courseRepository,
            IMapper mapper)
        {
            _repository = repository;
            _courseRepository = courseRepository;
            _mapper = mapper;
        }

        public ActionResult Index()
        {
            var subjects = _repository.GetAll();
            var subjectDtos = _mapper.Map<List<Subject>, List<SubjectDto>>(subjects);
            return View(subjectDtos);
        }

        public ActionResult Register()
        {
            var courses = _courseRepository.GetAll();
            var courseDtos = _mapper.Map<List<Course>, List<CourseDto>>(courses);

            return View(courseDtos);
        }

        [HttpPost]
        public ActionResult Register(SubjectDto model)
        {
            if (ModelState.IsValid)
            {
                var subject = _mapper.Map<SubjectDto, Subject>(model);

                var created = _repository.Create(subject);

                if (created != null)
                    return RedirectToAction("Index");
            }

            return View(model);
        }

        public ActionResult Edit(int id)
        {
            var subjectDto = _repository.GetById(id);
            return View(subjectDto);
        }

        [HttpPost]
        public ActionResult Edit(SubjectDto input)
        {
            var subject = _mapper.Map<SubjectDto, Subject>(input);
            var updatedSubject = _repository.Edit(input.Id, subject);
            return RedirectToAction("Index");
        }

        public ActionResult Delete(int id)
        {
            var deletedSubject = _repository.Delete(id);
            return RedirectToAction("Index");
        }

        public JsonResult GetAllCourses()
        {
            var courses = _courseRepository.GetAll();
            var courseDtos = _mapper.Map<List<Course>, List<CourseDto>>(courses);

            return Json(new { courseDtos }, JsonRequestBehavior.AllowGet);
        }
    }
}

LearningManagementSystem/Views/Subjects/Edit.cshtml
@using LearningManagementSystem.Models.Enums
@model LearningManagementSystem.Repositories.Subjects.Dtos.SubjectDto
@{
    ViewBag.Title = "Subject";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm("Edit", "Subjects", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()
    <h4>Edit Subject</h4>
    <hr />
    @Html.ValidationSummary("", new { @class = "text-danger" })
    <input type="hidden" name="Id" value="@Model.Id" />
    <input type="hidden" name="SelectedCourseId" id="SelectedCourseId" value="@Model.CourseId" />

    <div class="form-group">
        <label for="Title" class="col-md-2 control-label">Title</label>
        <div class="col-md-10">
            <input type="text" name="Title" id="Title" value="@Model.Title" class="form-control" required/>
        </div>
    </div>

    <div class="form-group">
        <label for="Semester" class="col-md-2 control-label">Semester</label>
        <div class="col-md-10">
            <select class="form-control" name="Semester" id="Semester" required>
                @foreach (var item in Enum.GetValues(typeof(Semester)))
                {
                    if (item.ToString() == Model.Semester.ToString())
                    {
                        <option value="@((byte)item)" selected>@(item.ToString())</option>
                    }
                    else
                    {
                        <option value="@((byte)item)">@(item.ToString())</option>
                    }
                }
            </select>
        </div>
    </div>

    <div class="form-group">
        <label for="Courses" class="col-md-2 control-label">Courses</label>
        <div class="col-md-10">
            <select class="form-control" name="CourseId" id="Courses" required>
            </select>
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" class="btn btn-warning" value="Update" />
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

<script type="text/javascript">
    window.onload = function () {
        if (window.jQuery) {

            var ddlCourses = $('#Courses');

            ddlCourses.empty();
            $.ajax({
                type: "GET",
                url: "/Subjects/GetAllCourses",
                data: {},
                contentType: "application/json",
                dataType: "json",
                success: function (response) {
                    
                    $.each(response.courseDtos, function (i, item) {
                        var selectedCourseId = $('#SelectedCourseId').val();
                        if (item.Id == parseInt(selectedCourseId)) {
                            ddlCourses.append('<option value="' + item.Id + '" selected>' + item.Title + '</option>');
                        } else {
                            ddlCourses.append('<option value="' + item.Id + '">' + item.Title + '</option>');
                        }

                        
                    });
                },
                error: function (xhr, status, error) {
                    alert("Result: " + status + " " + error + " " + xhr.status + " " + xhr.statusText)
                }
            });

        } else {
            alert("jQuery is not loaded");
        }
    }
</script>

LearningManagementSystem/Views/Subjects/Index.cshtml
@model IList<LearningManagementSystem.Repositories.Subjects.Dtos.SubjectDto>
@{
    ViewBag.Title = "Subjects";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@ViewBag.Title</h2>
<a href="@Url.Action("Register", "Subjects")" class="btn btn-primary">Register</a>
<div class="table-responsive">
    <table class="table">
        <thead class="thead-dark">
            <tr>
                <th scope="col">#</th>
                <th scope="col">Subject</th>
                <th scope="col">Semester</th>
                <th scope="col">Course</th>
                <th scope="col">Action</th>
            </tr>
        </thead>
        <tbody>
            @{ var index = 1; }
            @foreach (var subject in Model)
            {
                <tr>
                    <th scope="row">@(index++)</th>
                    <td>@subject.Title</td>
                    <td>@subject.Semester.ToString()</td>
                    <td>@subject.CourseTitle</td>
                    <td>
                        <a href="@Url.Action("Edit", "Subjects", new { subject.Id })">Edit</a> / <a href="@Url.Action("Delete", "Subjects", new { subject.Id })">Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

LearningManagementSystem/Views/Subjects/Register.cshtml
@using LearningManagementSystem.Models.Enums
@model  IEnumerable<LearningManagementSystem.Repositories.Courses.CourseDto>
@{
    ViewBag.Title = "Subject";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm("Register", "Subjects", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()
    <h4>Create a new subject</h4>
    <hr />
    @Html.ValidationSummary("", new { @class = "text-danger" })
    
    <div class="form-group">
        <label for="Title" class="col-md-2 control-label">Title</label>
        <div class="col-md-10">
            <input type="text" name="Title" id="Title" class="form-control" required />
        </div>
    </div>

    <div class="form-group">
        <label for="Semester" class="col-md-2 control-label">Semester</label>
        <div class="col-md-10">
            <select name="Semester" id="Semester" class="form-control" required>
                <option value=""></option>
                @foreach (var item in Enum.GetValues(typeof(Semester)))
                {
                    <option value="@((byte)item)">@(item.ToString())</option>
                }
            </select>
        </div>
    </div>


    <div class="form-group">
        <label for="CourseId" class="col-md-2 control-label">Course</label>
        <div class="col-md-10">
            <select class="form-control" name="CourseId" id="CourseId" required>
                <option value=""></option>
                @foreach (var course in Model)
                {
                    <option value="@course.Id">@course.Title</option>
                }
            </select>
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" class="btn btn-primary" value="Create" />
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}